language: python

python:
    - "2.7"

cache: pip

addons:
  apt:
    packages:
    - libasound2-dev
    - libfann-dev
    - portaudio19-dev
    - python-dev
    - swig

install:
    - ./bin/build-dev

script:
    - ./bin/test

after_success:
    - coveralls
